# Generated by Django 4.2.6 on 2023-10-12 11:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language_alter_bookinstance_id_bookinstance_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('afba73e4-e033-4d17-921a-be288c9bca8f'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
